CMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("app/",include("app.urls"))
]

app/urls.py
from django.urls import path
from app import views

app_name="app"

urlpatterns=[
    path("createcategory/",views.createcategory),
    path("createcategory/form/",views.createcategory),
    path("createuser/",views.createuser),
    path("createuser/form/",views.createuser),
    path("createarticle/",views.createarticle),
    path("createarticle/form/",views.createarticle),
    path("homepage/",views.listofcategories),
    path("articles_for_category/<int:cat_id>/",views.listof_articles_against_a_category, name="articles"),
    path("article_details/<int:id>/",views.article_detail, name="article_detail")
]

app/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"name: {self.name}"


class User(models.Model):
    username=models.CharField(max_length=100)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=50)

    def __str__(self):
        return f"username: {self.username},email: {self.email}, password: {self.password}"


class Article(models.Model):
    title=models.CharField(max_length=100)
    Content=models.CharField(max_length=500)
    publicationdate=models.DateTimeField(auto_now_add=True)
    Categories=models.ManyToManyField(Category)
    authors=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return f"title: {self.title}, content: {self.Content}, publicationdate: {self.publicationdate}, Categories: {list(self.Categories.all())}, author: {self.authors}"

app/forms.py
from django import forms
from .models import Category, User

class CreateCategoryForm(forms.Form):
    name=forms.CharField(max_length=100)

class CreateUserForm(forms.Form):
    username=forms.CharField(max_length=100)
    email=forms.EmailField()
    password=forms.CharField(max_length=50)

class CreateArticleForm(forms.Form):
    title=forms.CharField(max_length=100)
    Content=forms.CharField(max_length=5000)
    Category=forms.ModelMultipleChoiceField(Category.objects.all(),widget=forms.CheckboxSelectMultiple)
    author=forms.ModelMultipleChoiceField(User.objects.all(),widget=forms.CheckboxSelectMultiple)

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import CreateCategoryForm, CreateUserForm, CreateArticleForm
from .models import Category, User, Article
from django.utils import timezone

def createcategory(request):

    if request.method=="POST":
        form=CreateCategoryForm(request.POST)

        if form.is_valid():
            name=form.cleaned_data["name"]
            Category.objects.create(name=name)
            return HttpResponse("Category successfully created.")
        
    else:
        form=CreateCategoryForm()
        return render(request,"app/catform.html",{"form":form})
    


def createuser(request):

    if request.method=="POST":
        form=CreateUserForm(request.POST)

        if form.is_valid():
            name=form.cleaned_data["username"]
            email=form.cleaned_data["email"]
            password=form.cleaned_data["password"]
            User.objects.create(username=name,email=email,password=password)
            return HttpResponse("User successfully created.")
        
    else:
        form=CreateUserForm()
        return render(request,"app/createuser.html",{"form":form})
    


def createarticle(request):

    if request.method=="POST": 
        form=CreateArticleForm(request.POST)
        title=form.data["title"]
        Content=form.data["Content"]
        Categories=form.data.getlist('Category')

        categorylist=[]
        for id in Categories:
            cat=Category.objects.get(id=int(id))
            categorylist.append(cat)

        author_id=int(form.data["author"][0])
        author=User.objects.get(id=author_id)
        
        article=Article.objects.create(title=title,Content=Content,publicationdate=timezone.now(),authors=author)
        article.save()

        print("categorylist: ",categorylist)
        for item in categorylist:
            article.Categories.add(item)
            print("###################################article: ",article)
            article.save()
        return HttpResponse("Article successfully created.")
        
    else:
        form=CreateArticleForm()
        return render(request,"app/artform.html",{"form":form})
    

def listofcategories(request):
    categories=Category.objects.all()
    return render(request,"app/categories.html",{"categories":categories})


def listof_articles_against_a_category(request,cat_id):
    # print("testtesttesttesttesttesttesttesttesttesttesttest")
    # print("#######################cat_id",cat_id,"type: ",type(cat_id))
    category=Category.objects.get(id=int(cat_id))
    # print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@category: ",category)
    # articles=Article.objects.filter(Categories__in=[category])
    articles=Article.objects.filter(Categories__in=[category])
    print("articles: ",articles)
    return render(request,"app/artlist.html",{"articles":articles})


def article_detail(request,id):
    article=Article.objects.get(id=int(id))
    return render(request,"app/article_details.html",{"article":article})

app/templates/app/artform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="form/" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit">
    </form>
</body>
</html>

app/templates/app/article_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>{{article}}</div>
</body>
</html>

app/templates/app/artlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for article in articles %}
        <a href="{% url 'app:article_detail' id=article.id %}">{{article.title}}</a><br>
    {% endfor %}
</body>
</html>

app/templates/app/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for category in categories %}
        <div>{{category.id}}</div>
        <a href="{% url 'app:articles' cat_id=category.id %}">{{category}}</a>
    {% endfor %}
</body>
</html>

app/templates/app/catform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="form/" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit">
    </form>
</body>
</html>

app/templates/app/createuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="form/" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit">
    </form>
</body>
</html>